services:
  - type: web
    name: crack-detection
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 